
services:

  web-app:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    image: registry.gitlab.syncad.com/fiat/wojtek:${CM_FRONTEND_DOCKER_TAG:-local}
    restart: always
    ports:
      - "${PUBLISHED_PORT:-8080}:80"
    networks:
      - blocktrades
    volumes:
      - $PWD/docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - $PWD/docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - $PWD/docker/nginx/snippets:/etc/nginx/snippets:ro
      - $PWD/dist/routing-app/browser:/app:ro


networks:

  blocktrades:
    attachable: true
